//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLibrary.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class error
    {
        public decimal id { get; set; }
        public string errtitle { get; set; }
        public string date { get; set; }
        public string errmessage { get; set; }
        public string errtext { get; set; }
    }
}
