//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLibrary.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public decimal id { get; set; }
        public string type { get; set; }
        public string date { get; set; }
        public string runningTime { get; set; }
        public Nullable<decimal> OpenPrice { get; set; }
        public Nullable<decimal> TickerPrice { get; set; }
        public Nullable<decimal> OpenFund { get; set; }
        public Nullable<decimal> NetFund { get; set; }
        public Nullable<decimal> TradeQty { get; set; }
        public Nullable<decimal> SpanPrice { get; set; }
        public Nullable<decimal> OrderQty { get; set; }
        public Nullable<decimal> Earn { get; set; }
        public Nullable<decimal> RateYear { get; set; }
        public Nullable<System.DateTime> Open_Time { get; set; }
        public Nullable<decimal> HResetCount { get; set; }
        public Nullable<decimal> DealCount { get; set; }
        public Nullable<decimal> ResetCount { get; set; }
        public Nullable<decimal> RealEarn { get; set; }
        public Nullable<decimal> HDealCount { get; set; }
        public string LogOrders { get; set; }
        public string DBOrdersInfo { get; set; }
    }
}
